# ----
# Site

title: Repo Rangler
url: "https://reporangler.com"
baseurl:
google_analytics_key: UA-950385-32
google_maps_javascript_api_key: AIzaSyCERDcIsr71SlOssI6inY6uzF6FYTaQwnE

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
description: A dockerised, free, and open source package manager
logo: /siteicon.png
author:
  name: Christopher Thomas
  email: chris.thomas@antimatter-studios.com
  twitter: amstudios
  website: https://antimatter-studios.com
social:
  name: Repo Rangler
  links:
    - https://github.com/reporangler

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social_icons:
  - Twitter
  - GitHub
